name: 'coverage'
on:
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  CHART_REPO: "worldr/chart-worldr-mst"
  REGISTRY_HOST: "eu.gcr.io"
  REGISTRY_PATH: "compact-system-284111"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Copy this repo to the action folder
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.14.0

      ###################### SIGN IN TO ARTIFACT REGISTRY ############
      - name: save google credentials json
        run: echo '${{secrets.GOOGLE_GITHUB_SERVICE_ACCOUNT}}' | dd of=google.json
      - name: gcloud activate ServiceAccount
        run: gcloud auth activate-service-account --key-file=google.json --project=${{secrets.GCP_PROJECT}}
      ###################### BUILD AND PUSH ##########################
      - name: docker registry login
        run: docker login -u "_json_key" -p '${{secrets.GOOGLE_GITHUB_SERVICE_ACCOUNT}}' $REGISTRY_HOST
      - name: Install dependencies
        run: |
          echo Installing dependencies.
          npm run registry-login
          npm ci --userconfig=~/.npmrc

      - name: Run linter
        run: npm run lint

      - name: Run type checker
        run: npm run type-check

      - name: Generate coverage report
        id: coverage
        run: npx vitest --coverage

      - name: Add coverage report comment
        uses: davelosert/vitest-coverage-report-action@v2
