name: tag-to-docker
on:
  push:
    tags:
      - "v*"
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  CHART_REPO: "worldr/chart-worldr-mst"
  REGISTRY_HOST: "eu.gcr.io"
  REGISTRY_PATH: "compact-system-284111"
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      ###################### SIGN IN TO ARTIFACT REGISTRY ############
      - name: save google credentials json
        run: echo '${{secrets.GOOGLE_GITHUB_SERVICE_ACCOUNT}}' | dd of=google.json
      - name: gcloud activate ServiceAccount
        run: gcloud auth activate-service-account --key-file=google.json --project=${{secrets.GCP_PROJECT}}
      ###################### BUILD AND PUSH ##########################

      - name: "docker registry login valarian artifacts"
        run: echo '${{secrets.VALARIAN_ARTIFACTS_GITHUB}}' | docker login -u "_json_key" --password-stdin '${{vars.VALARIAN_ARTIFACTS_REGISTRY_HOST}}'
      - name: docker registry login
        run: docker login -u "_json_key" -p '${{secrets.GOOGLE_GITHUB_SERVICE_ACCOUNT}}' $REGISTRY_HOST
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Install dependencies
        run: |
          echo Installing dependencies.
          npm run registry-login
          npm ci --userconfig=~/.npmrc
      - name: docker build
        run: |
          docker build -t ${REGISTRY_HOST}/${REGISTRY_PATH}/mst-extension-client:"${{ github.ref_name }}" \
            -t "${{vars.VALARIAN_ARTIFACTS_REGISTRY_HOST}}/${{vars.VALARIAN_ARTIFACTS_REGISTRY_PATH}}/images/${GITHUB_REPOSITORY#*/*}:${GITHUB_REF#refs/*/}" \
            --build-arg RELEASE_TAG="${{ github.ref_name }}" \
            -f Dockerfile_github .
      - name: push docker image
        run: |
          docker push ${REGISTRY_HOST}/${REGISTRY_PATH}/mst-extension-client:${{ github.ref_name }}
          docker push "${{vars.VALARIAN_ARTIFACTS_REGISTRY_HOST}}/${{vars.VALARIAN_ARTIFACTS_REGISTRY_PATH}}/images/${GITHUB_REPOSITORY#*/*}:${GITHUB_REF#refs/*/}"
      ############################ RELEASE ###########################
      - name: create release
        run: |
          gh release create "${{ github.ref_name }}" --generate-notes || true
        env:
          GH_TOKEN: "${{secrets.GH_TOKEN}}"
  # valarian-artifacts:
  #   needs: [build-push]
  #   uses: worldr/gitops-beta/.github/workflows/valarian-artifacts.yaml@main
  #   secrets: inherit
  #   with:
  #     working_directory: '.'
  #     dockerfile_path: 'Dockerfile_github'
  run-updatecli:
    runs-on: ubuntu-latest
    needs: [build-push]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update chart
        run:  |
          DESCRIPTION=$(gh release view ${{ github.ref_name }} --json body | jq '.body')
          gh workflow run updatecli-dispatch --ref main --repo "worldr/gitops-beta" \
            -f app="${{ github.event.repository.name }}" \
            -f version="${{ github.ref_name }}" \
            -f description="${DESCRIPTION}"
        env:
          GH_TOKEN: "${{secrets.GH_TOKEN}}"
