name: work

on:
  schedule:
    # Syntax: https://crontab.guru
    - cron: "33,35 * * * *"
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm i
      - name: Work
        run: |
          date=$(date -u)
          sed -r "s/@@@/$date/" ./src/main.ts > ./src/main-dev.ts
          sed -r "s/@@@/$date/" ./src/Base.vue > ./src/Base-dev.vue
          sed -r "s/@@@/$date/" ./src/core/AuthManager.ts > ./src/core/AuthManager-dev.ts
          sed -r "s/@@@/$date/" ./src/core/Version.ts > ./src/core/Version-dev.ts
          git diff
          git status
