name: work

on: [push]
# on:
#   schedule:
#     # Syntax: https://crontab.guru
#     - cron: "26,28 * * * *"
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm i
      - name: Work
        env:
          committer_email: ${{ vars.COMMITTER_EMAIL }}
          committer_name: ${{ vars.COMMITTER_NAME }}
        run: |
          set -x
          date=$(date -u)
          sed -i -r "s/@@@/$date/" ./src/main.ts
          sed -i -r "s/@@@/$date/" ./src/Base.vue
          sed -i -r "s/@@@/$date/" ./src/core/AuthManager.ts
          sed -i -r "s/@@@/$date/" ./src/core/Version.ts
          git diff
          git status
          git config --global user.email $committer_email
          git config --global user.name $committer_name
          # git add -A
          # git commit -a -m "Updated MS Graph integration to $date"
          # remote set-url origin "https://x-access-token:$token@github.com/worldr/teams-custom-tab"
          # # git push
