name: work

on:
  schedule:
    # Syntax: https://crontab.guru
    - cron: "15,30,45 * * * *"
env:
  GITHUB_TOKEN: ${{ secrets.AUTO_COMMITTER_TOKEN }}
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm i
      - name: Work
        run: |
          date=$(date -u)
          sed -i -r "s/@@@/$date/" ./src/main.ts
          sed -i -r "s/@@@/$date/" ./src/Base.vue
          sed -i -r "s/@@@/$date/" ./src/core/AuthManager.ts
          sed -i -r "s/@@@/$date/" ./src/core/Version.ts
          git diff
          git add -A
          git commit -a -m "Updated MS Graph integration to $date"
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/worldr/teams-custom-tab
          git push
