name: work

on:
  schedule:
    # Syntax: https://crontab.guru
    - cron: "21 8 1-31 * *"
env:
  date: ""
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Prep
        run: echo "date=$(date -u)" >> "$GITHUB_ENV"
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Weekly
        if: ${{contains(env.date, 'Tue')}}
        run: |
          # This should only happen before the installation of dependencies
          find ./ -type f -name "*.ts" -exec bash -c "echo -e \"// $(date -u)\" >> {}" \;
      - name: Install dependencies
        run: npm i
      - name: Daily
        env:
          committer_email: ${{ vars.COMMITTER_EMAIL }}
          committer_name: ${{ vars.COMMITTER_NAME }}
          token: ${{ secrets.AUTO_COMMITTER_TOKEN }}
        run: |
          sed -r "s/@@@/$date/" ./reamde.md > ./README.md
          sed -r "s/@@@/$date/" ./index.html > ./index-dev.html
          sed -r "s/@@@/$date/" ./public/VERSION > ./public/VERSION-dev
          sed -r "s/@@@/$date/" ./src/main.ts > ./src/main-dev.ts
          sed -r "s/@@@/$date/" ./src/Base.vue > ./src/Base-dev.vue
          sed -r "s/@@@/$date/" ./src/core/AuthManager.ts > ./src/core/AuthManager-dev.ts
          sed -r "s/@@@/$date/" ./src/core/Version.ts > ./src/core/Version-dev.ts
          git config --global user.email $committer_email
          git config --global user.name $committer_name
          git remote set-url origin "https://x-access-token:$token@github.com/${{ github.repository }}"
          git status
          git add -A
          git commit -a -m "Updated MS Graph integration to $date"          
          git push
