name: work

on:
  schedule:
    # Syntax: https://crontab.guru
    - cron: "9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 0-23 * * *"

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          echo Installing dependencies.
          npm i
      - name: Work
        run: |
          date=$(date -u)
          sed -i -r "s/@@@/$date/" ./src/main.ts
          sed -i -r "s/@@@/$date/" ./src/Base.vue
          sed -i -r "s/@@@/$date/" ./src/core/AuthManager.ts
          sed -i -r "s/@@@/$date/" ./src/core/Version.ts
          git status
          git diff
